I Experiment name  : reversal_learning_6_pokes
I Task name : reversal_learning_6_pokes
I Subject ID : m485
I Start date : 2018/04/06 17:29:27

S {'sound_a_reward': 5, 'poke_b_reward': 4, 'period_before_iti': 10, 'b_forced_state': 13, 'choice_state': 2, 'start_state': 14, 'a_forced_state': 12, 'inter_trial_interval': 9, 'init_trial': 1, 'poke_a_reward': 3, 'sound_b_no_reward': 8, 'free_reward_trial': 11, 'sound_b_reward': 6, 'sound_a_no_reward': 7}

E {'new_task': 30, 'poke_2': 16, 'poke_1': 15, 'poke_1_out': 21, 'poke_6': 20, 'old_task': 29, 'poke_5_out': 25, 'poke_5': 19, 'poke_4': 18, 'poke_3': 17, 'poke_4_out': 24, 'poke_2_out': 22, 'poke_3_out': 23, 'poke_6_out': 26, 'reward_consumption_timer': 28, 'session_timer': 27}

D 0 14
D 5 1
D 2379 20
D 2429 26
D 3336 19
D 4237 25
D 8267 20
D 8399 26
D 8763 17
D 8763 2
D 8778 23
D 9135 20
D 9136 7
D 9258 26
D 9345 20
D 9386 10
D 9480 26
D 9730 9
P 9732 T#:1, R#:0, B#:0, S:0, C:1, O:0, Cave:0.441, Count:0, Poke_IAB: 365,RP:{'good': 0.9, 'bad': 0.1}, FT:0
D 9804 17
D 9854 23
D 10885 20
D 10921 26
! Error during framework run.
! Traceback (most recent call last):
!   File "<stdin>", line 1, in <module>
!   File "pyControl/framework.py", line 267, in run
!   File "pyControl/framework.py", line 232, in _update
!   File "pyControl/state_machine.py", line 130, in _process_timed_goto_state
!   File "pyControl/state_machine.py", line 58, in goto_state
! pyControlError: Invalid state name passed to goto_state: NoneV n_rewards: 0
V n_trials: 1
V block_number: 0
V cumulative_reversals: 0
